name: example_project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  redux: 3.0.0
  http: 0.12.0+2
  redux_epics: 0.10.6
  json_serializable: ^3.2.5
  flutter_redux: 0.5.3
  google_fonts: ^0.3.9
  flutter_secure_storage: 3.2.1+1
  flutter_redux_navigation: 0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build_runner: 1.7.2
  json_serializable: 3.2.5
  flutter_launcher_icons: ^0.7.3

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700